lib/geocoder/results/yandex.rb, test/fixtures/yandex_no_administrative_area, test/unit/result_test.rb
I was running into exceptions calling `#city` on location results for coordinates in certain regions. It appears that sometimes Yandex does return `AddressDetails.Country` in the JSON, but the `Country` key doesn't include `AdministrativeArea`, which can lead to an `undefined method `has_key?' for nil:NilClass` error.
This is just a quick patch for the issue by checking for the existence of `AdministrativeArea` before checking for the key below that. If you'd prefer a different approach, let me know.
=> Fix Yandex city error when JSON does not include 'AdministrativeArea'

geocoder.gemspec
I was trying to determine the licenses for my dependencies. I found that the RubyGems API will return the license, but only if it is specified in your gemspec file.
=> Add license to gemspec

lib/geocoder/lookup.rb
It makes it easier to add a custom lookup class by adding an entry in
the correct service array.
=> Store service arrays in instance variable

lib/geocoder/results/freegeoip.rb
It seems that freegeoip.net now returns `zip_code` (with an underscore) instead of `zip_code`. This pull request handles both responses.
=> Handle freegoip's updated response format

lib/geocoder/query.rb, test/unit/query_test.rb
=> Force specfify ip_lookup on search, even when ip_address? fails

lib/geocoder/configuration.rb, lib/geocoder/lookup.rb, lib/geocoder/lookups/base.rb, lib/geocoder/lookups/maxmind_geoip2.rb, lib/geocoder/results/maxmind_geoip2.rb, test/fixtures/maxmind_geoip2_1_2_3_4, test/test_helper.rb, test/unit/lookup_test.rb, test/unit/lookups/maxmind_geoip2_test.rb
Connected to #594 
I know that geocoder currently has a geoip2 lookup defined which uses Hive::Geoip2 
- though I believe this is the lite version using the free database? 
- should I be adding this functionality to :geoip2 directly and have some logic that understands to use the Precision Service API?
I ran the test cases, but locally `bundle exec rake test` seems to indicate that the test_helper's version of MaxmindGeoip2 might not actually be used 
- Do I have something configured wrong for the tests?
=> Adding MaxMind's GeoIP2 Precision Service API

README.md, lib/geocoder/request.rb, test/fixtures/freegeoip_74_200_247_60, test/unit/request_test.rb
The original impetus for this was to fix exceptions thrown due to HTTP headers set by cruddy proxies, e.g.:
* an exception would be thrown when HTTP_X_FORWARDED_FOR was set to ","
Other problems noticed along the way, and fixed:
* `location` is vulnerable to trivial IP spoofing via HTTP headers; this has been added to the docs, and an alternate but less accurate `paranoid_location` provided.
* `location` did not filter out proxies trusted by Rack, so for people running Rack behind their own proxy (as recommended, but frequently ignored), `location` would always return the location of that proxy.  `location` and `paranoid_location` now respect Rack/Rails trusted_proxies config
* there's a whole zoo of nonstandard HTTP headers used by proxies to store the upstream address, a few more of …
=> Improve request.location(), add request.paranoid_location()

lib/geocoder/lookups/esri.rb
stacktrace example:
/gems/geocoder-1.2.6/lib/geocoder/lookups/esri.rb:24 in "results"
/gems/geocoder-1.2.6/lib/geocoder/lookups/base.rb:47 in "search"
/gems/geocoder-1.2.6/lib/geocoder/query.rb:11 in "execute"
/gems/geocoder-1.2.6/lib/geocoder.rb:20 in "search"
/gems/geocoder-1.2.6/lib/geocoder/stores/base.rb:111 in "do_lookup"
/gems/geocoder-1.2.6/lib/geocoder/stores/active_record.rb:259 in "geocode"
=> fix issue with empty? doc[‘locations’] on ESRI lookup for some addresses

lib/geocoder/results/geoip2.rb
sometime geoip2 database misses the mark or we do not get complete data, using a consistent fetch method we can avoid NoMethodError: undefined method `[]' for nil:NilClass
=> GeoIP2 handling of missing data

lib/geocoder/ip_address.rb, test/unit/ip_address_test.rb
Ruby has already good Regex for checking IP addresses 
```Resolv::IPv4::Regex``` and ```Resolv::IPv6::Regex```
No need to reinvent the wheel.
666.65.123.94 - technically or not, this address is not valid
=> use builtin libs to validate ips

.gitignore, .travis.yml, Gemfile, Rakefile, gemfiles/Gemfile.ruby1.9.3, test/database.yml, test/db/migrate/001_create_test_schema.rb, test/test_helper.rb, test/unit/near_test.rb
Summary:
Enabled running tests using `rake test DB=`, with options mysql, sqlite, and postgres. If DB is not set (or is nil) the tests will run as before (using mocked ActiveRecord::Base).
Also configured to run them on travis-ci
=> Enable testing different database environiments

geocoder.gemspec
Will make the exported gem size smaller.
Before: 1.1M
After: 516k
Note: size found using `bundle list geocoder` then `du -h` on the file path it gave.
=> Don't include test files in the exported gem

lib/geocoder/lookups/baidu.rb, lib/geocoder/lookups/baidu_ip.rb, lib/geocoder/lookups/base.rb, lib/geocoder/lookups/google_places_details.rb, lib/geocoder/lookups/maxmind_geoip2.rb, lib/geocoder/lookups/smarty_streets.rb, lib/geocoder/lookups/telize.rb
A single function to override on a `Lookup` class
that makes it clear which lookups support which protocols.
This is an alternative fix for
https://github.com/alexreisner/geocoder/pull/863
=> `lookup.supported_protocols`

lib/geocoder/lookups/yandex.rb
I added supported_protocols method with https only.
=> Fix yandex geocoder redirect to https

lib/geocoder/exceptions.rb, lib/geocoder/lookups/base.rb
Hi, thanks for the awesome work on this gem!
Ruby's timeout API is [inherently unsafe](http://www.mikeperham.com/2015/05/08/timeout-rubys-most-dangerous-api/). This PR replaces it with a safe method.
Open timeouts raise `Net::OpenTimeout` and read timeouts raise `Net::ReadTimeout`.  Both inherit from `Timeout::Error` (which is also defined as `TimeoutError`), so this should be a safe change, but we could always catch and re-raise a `Timeout::Error` you think that's better.
Let me know your thoughts. Thanks!
=> Safer timeouts

lib/geocoder/request.rb, test/unit/request_test.rb
See #906 safe_location and location should not rely on the same variable,
otherwise calling one before the other will yield unexpected results
and could even cause a security risk if location is called before
safe_location
=> Fix #906 - Use different memoization variables for request

.travis.yml, gemfiles/Gemfile.rails3.2, gemfiles/Gemfile.rails4.1, test/unit/logger_test.rb, test/unit/mongoid_test.rb
Work in Progress
-------------------------
Connected to #813 
There are very few test failures so far with rails 4.1 gemfile.
The mongoid one is due to:
```
#3037 Model indexes are no longer stored in an index_options hash on the model class. Instead, an array named index_specifications now exists on the class which contains a list of Indexable::Specification objects. This is so we could properly handle the case of indexes with the same keys but different order.
```
Non-backward compatible change in Mongoid 4.0. I think this is only in our test case that `index_options` is used.
=> Testing against diff versions of rails

README.md
Looking through the README, the only mention of the format of `coordinates` was under the MongoDB section which is all the way at the bottom of the file.
=> Emphasize form of coordinates in README

lib/maxmind_database.rb
Can't use a custom-located CSV when importing the maxmind DB.  This is an issue for Heroku users.
=> Pass in dir variable when retreiving data files in Maxmind insert task

lib/geocoder/results/mapquest.rb
Trivial change to expose the County in the mapquests results. 
Test cases run and I've tested the gem in my own application.
=> Add county accessor for map quest results

test/unit/test_mode_test.rb
for #903, even though there was no issue this time, we should add a test to ensure no issue will be introduced in the future.
=> Test that stubbing with an invaid address works

lib/geocoder/lookups/base.rb
Hi, I haven't done many PR so hopefully I did this one right.
I was testing the latest version of geocoder on my rails project on ruby 1.9.3 and I ran into this error:
```
>> result = Geocoder.search("192.0.180.56", lookup: :geocoder_ca, timeout: 60)
NameError: uninitialized constant Net::OpenTimeout
from /home/user/.rvm/gems/ruby-1.9.3-p484/gems/geocoder-1.2.11/lib/geocoder/lookups/base.rb:286:in `rescue in make_api_request'
...
```
This line was trying to rescue Net::OpenTimeout and Net::ReadTimeout which were introduced in July by 8b76c4520e05403b2b4dd7cfca07929ca7d77e8a. [Net::OpenTimeout](http://yard.ruby-doc.org/stdlib-2.0/Net/OpenTimeout.html) and [Net::ReadTimeout](http://yard.ruby-doc.org/stdlib-2.0/Net/ReadTimeout.html) seems to have been introduced in Ruby 2.0 but both are a …
=> Replace timeout exception so its compatible with Ruby 1.9.3 too.

lib/generators/geocoder/config/templates/initializer.rb
Move away from generating a `geocoder.rb` initializer with old school ruby hash syntax in favor of the new/current style.
=> Update hash syntax

README.md, lib/geocoder/lookups/mapbox.rb, lib/geocoder/results/mapbox.rb, test/unit/lookups/mapbox_test.rb, test/unit/result_test.rb
Three change for the Mapbox geocoder:
- Added a new option `:dataset` for Mapbox to specific datasets other than the default `"mapbox.places"`
- Use [long,lat] rather than [lat,long] with Mapbox API
- Added tests more generally to catch this sort of bug
=> Mapbox fixes and dataset option

README.md, lib/geocoder/stores/active_record.rb, lib/tasks/geocoder.rake
Added a batch reverse geocoding task; works just like the batch geocoding one but checks for null `address` rather than lat and lon.
=> Add batch reverse geocoding task

README.md, lib/geocoder/lookups/telize.rb, test/unit/lookup_test.rb, test/unit/lookups/telize_test.rb
The Telize API has changed:
1) Moved to Mashape, different URL
2) Now requires an API key
3) Now uses HTTPS
More info: http://www.telize.com/
=> Update Telize lookup to use new API endpoint

lib/geocoder/lookups/geoip2.rb
Is there a particular reason why the GeoIP2 lookup is treated as a singleton?
On every call, you're:
- opening the MaxMind database
- doing a lookup
- closing the MaxMind database
This PR allows the caller to reuse the same database handle.
Tests seem to be happy.
=> Create a GeoIP2 object for reuse

lib/geocoder/results/esri.rb, test/fixtures/esri_austin_tx, test/fixtures/esri_new_york_ny, test/fixtures/esri_washington_dc, test/unit/lookups/esri_test.rb
When querying for a city directly (e.g. Washington DC), the current esri result object returns a blank city. 
I tested a wide range of cities and determined that the city attribute is blank for esri results with the types 'City', 'State Capital', and 'National Capital'. However the PlaceName attribute contains the correct city name. I believe this is because the city itself is coming back as a POI, so there's not much point in them duplicating the city value.
This change returns the city by looking at the PlaceName attribute if the result is a city POI. I included tests with the three city location types I was able to determine. I couldn't find a list anywhere in esri's docs, but I queried for a lot of cities and only found these three types.
Let me know if you have any feedback, thanks!
=> Retrieve city when esri query returns a city POI

lib/geocoder/results/google.rb
Pretty self-explanatory.  It's great you can access it via `data` but these are very useful fields to expose.
=> Google geocoder results - expose partial_match and place_id fields

lib/geocoder/lookups/maxmind_local.rb
Database index index_maxmind_geolite_city_blocks_on_end_ip_num_range was not used while querying the database by IP address.
Before:
```
=> EXPLAIN ANALYZE SELECT l.country, l.region, l.city, l.latitude, l.longitude FROM maxmind_geolite_city_location l WHERE l.loc_id = (SELECT b.loc_id FROM maxmind_geolite_city_blocks b WHERE b.start_ip_num <= 2467698198 AND 2467698198 <= b.end_ip_num LIMIT 1);
QUERY PLAN
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Index Scan using index_maxmind_geolite_city_location_on_loc_id on maxmind_geolite_city_location l  (cost=0.14..4.14 rows=1 width=31) (actual time=89.990..89.991 rows=1 loops=1)
Index Cond: (loc_id = $0)
InitPlan …
```
=> Removed 'LIMIT 1' in maxmind local lookup that prevented from using database index.

lib/geocoder/calculations.rb
I just spent a few hours trying to get this function to work, then realized I had my parameters in the wrong order. I was following the order listed in the comment, rather than the actual method definition! *facepalm* Anyhow, this fixes the comment, for the next person to read it.
=> Fix Geocoder::Calculations.endpoint comment

lib/geocoder/lookup.rb, test/test_helper.rb
Connected to #898 
@alexreisner The reason you've required all the lookups seemed to have been for the Test lookup. So I required that by default and then required the other lookups as needed.
For the test_helper, the lookups which are monkey patched needed to be required.
An example of one which isn't required in the test_helper is `yahoo` and at minimum the lookups are all tested in LookupTest `test_search_returns_empty_array_when_no_results`.
=> Require only needed lookup

README.md, lib/geocoder/configuration.rb, lib/geocoder/lookups/yahoo.rb
https://developer.yahoo.com/boss/placefinder/
the Yahoo lookup will be fully removed via:
https://github.com/alexreisner/geocoder/pull/985
@alexreisner - I'm not sure whether a warning in `Lookup.get` or in `Lookup::Yahoo.results` makes more sense. Let me know what you think & I will remove one of the warnings.
=> Warn that the Yahoo BOSS Placefinder API is being discontinued.

lib/geocoder/results/bing.rb, lib/geocoder/results/esri.rb, lib/geocoder/results/google.rb, lib/geocoder/results/here.rb, lib/geocoder/results/nominatim.rb, lib/geocoder/results/opencagedata.rb, lib/geocoder/results/ovi.rb, lib/geocoder/results/yahoo.rb, lib/geocoder/results/yandex.rb, test/unit/lookups/bing_test.rb, test/unit/lookups/esri_test.rb, test/unit/lookups/google_test.rb, test/unit/lookups/here_test.rb, test/unit/lookups/nominatim_test.rb, test/unit/lookups/opencagedata_test.rb, test/unit/lookups/ovi_test.rb, test/unit/lookups/yahoo_test.rb, test/unit/lookups/yandex_test.rb
Several providers return bounding box coordinates for the recommended area to display on a map for a particular query. It thought would be useful to expose this in the same format as bounding boxes are usually passed around in Geocoder.
Feedback would be welcome on naming and format. I see both `[[sw_lat, sw_lon], [ne_lat, ne_lon]]` and `[sw_lat, sw_lon, ne_lat, ne_lon]` being used, but I thought the former might be more clear.
The same method could probably be added to a lot of other providers as well. If you think this is a good idea, I could skim through the fixture data and add the ones I can verify by myself. :)
=> Add viewport method to results that provide one

README.md, examples/reverse_geocode_job.rb, lib/generators/geocoder/config/templates/initializer.rb, lib/geocoder/configuration.rb, lib/geocoder/lookups/base.rb, test/test_helper.rb, test/unit/error_handling_test.rb
`TimeoutError` is deprecated in Ruby 2.3.0, causing some of the warnings seen in #976.
It has been an alias for `Timeout::Error` starting in Ruby 1.8.0, and should be safe to replace. Here's the original commit from 2003: https://github.com/ruby/ruby/commit/9d22a06ea06e9bec5030fd6e2c8481958fcd30d9
=> Replace TimeoutError with Timeout::Error

lib/geocoder/lookups/freegeoip.rb
I uncovered a small issue when switching from Yahoo BOSS to Google (with API, which requires enabling :use_https).  Because the Freegeoip.rb file is missing a supported_protocols method, it attempts to do an https lookup for IP lookups when enabling :use_https.
I already tested this on my setup and it appears to resolve the issue, with lookups/base.rb detecting that https is not supported for Freegeoip
=> Add supported_protocols to Freegeoip.rb lookup

README.md
Yesterday, I had to check out the library and search through code to find how to setup `:maxmind_geoip2` as an IP Address Service.
The main goal was _basic_auth_ params. So I think of can be helpful to have this information on the `README.md`.
=> add maxmind_geoip2 setup to README.md

README.md, lib/geocoder/lookup.rb, lib/geocoder/lookups/latlon.rb, lib/geocoder/results/latlon.rb, test/fixtures/latlon_6000_universal_blvd, test/fixtures/latlon_invalid_key, test/fixtures/latlon_no_results, test/test_helper.rb, test/unit/lookups/latlon_test.rb
Adds support for the geocoding (street services) at [LatLon.io](https://latlon.io)
=> Add support for the LatLon.io geocoder service

test/unit/lookups/geoportail_lu_test.rb
Took a shot at fixing this warning, hopefully I'm doing this right. The Geocoder API warning occurs in the test_no_results unit test, where no results being returned is the expected behaviour. Added a warning suppression line based on prior example.
=> Suppress Geocoder API warning when no results are returned

Rakefile
=> Remove verbose from rake options due to jruby and rbx failing on travis

lib/geocoder/lookups/freegeoip.rb, lib/geocoder/results/freegeoip.rb
Given 'freegeoip.net' is down for the foreseeable future ([ref here](https://twitter.com/fiorix_/status/715892818758221825)) and a clone has been established at 'freegeoip.net' I propose updating the default IP lookup to the latter. This is also somewhat in response to issue [#1009](https://github.com/alexreisner/geocoder/issues/1009)
=> change freegeoip lookup's host from freegeoip.net to freegeoip.io

lib/geocoder/lookups/google.rb, test/unit/lookups/google_test.rb
Hey guys.
Just wondering if it would be possible have the option to return `result_type` from the google geocoder reverse lookup as seen here.
https://developers.google.com/maps/documentation/geocoding/intro#ReverseGeocoding
=> Add result_type as option for google lookup

Gemfile, gemfiles/Gemfile.rails3.2, gemfiles/Gemfile.rails4.1, gemfiles/Gemfile.ruby1.9.3, lib/geocoder/lookups/base.rb, lib/geocoder/lookups/google.rb, test/test_helper.rb, test/unit/lookup_test.rb, test/unit/lookups/google_test.rb
Fixes #1034 
About the test, I didn't feel comfortable changing such a crucial piece of the code without at least making a test that passes :) . Basically what I did is rename the `:make_api_request` to `:make_http_api_request`, and then verify the behavior of the latter.
=> Disable SSL v2 and v3 if ssl enabled

lib/geocoder/lookups/esri.rb
This fixes the test added in #1053 by merging the new token with the old esri config.
=> fix merging esri config when generating a token

lib/geocoder/configuration.rb, lib/geocoder/lookups/esri.rb, test/unit/configuration_test.rb
This functionality is currently implemented by the ESRI lookup but is potentially useful to other lookups as well.
=> Add Method for Merging Lookup Configuration

lib/geocoder/lookups/esri.rb, test/unit/lookups/esri_test.rb
The Esri geocoder also takes a `sourceCountry` parameter which forces the geocoding requests to use a particular country's geocoder.
I originally thought about making a more significant change that would allow arbitrary parameters to be passed through to the request, but in reviewing the Esri [API docs](https://developers.arcgis.com/rest/geocode/api-reference/geocoding-find.htm) there's really only this `sourceCountry` and the `forStorage` ones that make sense to set globally. The others would be better off being able to set per request, so I'll leave that for another time.
=> add `source_country` parameter for esri geocoder

test/unit/lookups/esri_test.rb
This stubs the `generate_token` method only within this test. This brings the test coverage of `Geocoder::Lookup::Esri` closer to 100%.
=> adds test for esri token generation from client credentials

lib/geocoder/lookups/smarty_streets.rb, test/unit/lookups/smarty_streets_test.rb
SmartyStreets is permanently changing their ZIP Code API endpoint by
**June 22 at 9am Mountain Time**.  The legacy API endpoint is available
until the 22nd.  http://status.smartystreets.com/incidents/4hjpfqh9q2k7
This change basically changes the API endpoint and updated the tests to
reflect the change.
=> Change SmartyStreets Zipcode API

lib/geocoder/request.rb
Maintains Ruby 2.0 compatibility in `Geocoder::Request` where `Module#include` is a private method.
Once pulled in this should fix #1066 
Thanks.
=> Bug no method action dispatch request.include

test/unit/lookups/esri_test.rb
Having a first argument to a method call without parentheses in Ruby 2.3.x that is a "/" delimited regular expression literal results in…
warning: ambiguous first argument; put parentheses or a space even after `/' operator
This can be fixed by either using parentheses around the arguments or using the alternative syntax for literal regular expressions. It seems cleanest to me to use the alternative syntax rather than adding the parentheses when similar nearby code lines all do not use the parentheses.
=> Fix ambiguous 1st argument warnings in Ruby 2.3.x

lib/tasks/geocoder.rake
In Rails 5, `rake geocode:all` crashes:
```
$ rake geocode:all CLASS=Whatzit
rake aborted!
ArgumentError: comparison of Fixnum with nil failed
/Users/paul/.rvm/gems/ruby-2.2.2/gems/activerecord-5.0.0/lib/active_record/relation/batches.rb:217:in `<'
/Users/paul/.rvm/gems/ruby-2.2.2/gems/activerecord-5.0.0/lib/active_record/relation/batches.rb:217:in `block in in_batches'
/Users/paul/.rvm/gems/ruby-2.2.2/gems/activerecord-5.0.0/lib/active_record/relation/batches.rb:198:in `loop'
/Users/paul/.rvm/gems/ruby-2.2.2/gems/activerecord-5.0.0/lib/active_record/relation/batches.rb:198:in `in_batches'
/Users/paul/.rvm/gems/ruby-2.2.2/gems/activerecord-5.0.0/lib/active_record/relation/batches.rb:120:in `find_in_batches'
/Users/paul/.rvm/gems/ruby-2.2.2/gems/activerecord-5.0.0/lib/active_record/relation …
```
=> Prevent rake task crash when BATCH not specified

lib/geocoder/request.rb
Ever since the code change in #1061, if a Rack application loads both Rails and Sinatra simultaneously (e.g., both are included in the same middleware stack for handling different routes), then only `ActionDispatch::Request` will be enhanced with geocoder methods and not `Rack::Request`, causing `request#location` to be undefined in the Sinatra route. (My use-case is currently Rails 4.2, but presumably affects Rails 5 as well.)
The fix in this PR changes the `if ... elsif` conditional to instead use two separate conditionals.
=> always add geocoder to Rack::Request if defined

lib/geocoder/lookups/ipinfo_io.rb, lib/geocoder/results/ipinfo_io.rb, test/unit/lookups/ipinfo_io_test.rb
Patch https://github.com/alexreisner/geocoder/pull/997
When query loopback address using ipinfo.io,
```
Geocoder.search("127.0.0.1")
```
This error is raised because an invalid result is returned:
```
undefined method `split' for nil:NilClass
geocoder (1.3.7) lib/geocoder/results/ipinfo_io.rb, line 11
```
Changes:
- Returns a valid result when query loopback address in ipinfo.io
- Fix incorrect method definition for extra result attributes i.e. `result.ip`, `result.region`, `result.postal`
=> Fix result of ipinfo.io for loopback address (127.0.0.1)

README.md
The method `#reset` for clearing stubs
was previously unmentioned in the README
=> Add Lookup::Test.reset to README 

README.md
`:host` must be nested within the `:dstk` key
in order to be included in the configuration 
for the lookup.
=> Fix README regarding dstk :host configuration

lib/geocoder/calculations.rb
Refactored `calculations::extract_coordinates` and `calculations::coordinates_present?`
`coordinates_present?
`Checks whether an argument matches validating criteria (numeric, not NaN), rather than returning false when matching invalidating criteria.
Also replaced `.to_s == NaN` with` .to_f..nan? `
`extract_coordinates` 
Now calls `coordinates_present?` to validate the array, instead of comparing four booleans and initialising extra vars.
=> Refactor calculations

lib/geocoder/results/mapbox.rb, test/fixtures/mapbox_Shanghai,_China, test/unit/result_test.rb
Some mapbox results come back without context. The mapbox result class was assuming that this context is always present. This patch changes that assumption.
Also, extract a couple of methods.
=> Fix mapbox results

lib/geocoder/calculations.rb
Instead of converting the Earth's radius to different units on-the-fly, it's calculated once on file load. Here's a before/after benchmark of `distance_between`:
``` ruby
Benchmark.measure do 
1_000_000.times do 
Geocoder::Calculations.distance_between [47.858205,2.294359], [40.748433,-73.985655]
end
end
user     system      total         real
before:   7.840000   0.010000   7.850000 (  7.853178)
after:    5.800000   0.010000   5.810000 (  5.821909)
```
The changes are backwards compatible. These aren't used internally and can be deprecated if you like:
```
EARTH_RADIUS
#to_kilometers
#to_miles
#to_nautical_miles
#mi_in_km
#km_in_mi
#km_in_nm
#nm_in_km
```
=> improved performance of various calculations

gemfiles/Gemfile.ruby1.9.3
the URL had an extra slash in it in the readme
=> Fixed typo in google API Signup URL

lib/tasks/geocoder.rake
Changes batching in the rake task to work using a loop instead of the find_each method which does not work with Mongoid. This should fix #1126.
=> Use manual batching in rake task

README.md, lib/geocoder/lookup.rb, lib/geocoder/lookups/google.rb, lib/geocoder/lookups/google_places_search.rb, lib/geocoder/results/google_places_search.rb, test/fixtures/google_places_search_madison_square_garden, test/fixtures/google_places_search_no_results, test/unit/lookups/google_places_search_test.rb, test/unit/result_test.rb
Hello. This is my attempt to integrate gogole places search lookup, as discussed on https://github.com/alexreisner/geocoder/issues/1128 . 
This query return way less data than other google query though, so many method will just return blank.
What do you think?
=> Google Places Search Lookup

lib/geocoder/results/smarty_streets.rb, test/fixtures/smarty_streets_96628, test/unit/lookups/smarty_streets_test.rb
Currently when running a search via `Geocoder.coordinates("a zip code")` for certain zip codes (eg 96628) that exist, but for some reason doesn't exist in the Smarty Streets database, the coordinates method returns `[nil,nil]` which is not very useful. What would be more useful is if the method returns an actual nil value. These changes enable that.
=> Update smarty streets search results coordinates method to return nil 

lib/geocoder/request.rb, test/unit/request_test.rb
Hello. This PR is about the issue #933. 
I created `geocoder_remove_port_from_addresses(ip_addresses)` and `geocoder_reject_non_ipv4_addresses(ip_addresses)` to insure that the `ip_addresses` contains the valid ip address without port number. Then these two method are called in `geocoder_spoofable_ip` method.
I added tests for the cases when the `ip_addresses` includes port numbers and invalid ip addresses.
=> 933 remove port from geocoder_spoofable_ip

lib/geocoder/results/geoip2.rb, test/unit/lookups/geoip2_test.rb, test/unit/lookups/maxmind_geoip2_test.rb
Non-breaking (i hope) implementation of #1144
Maxmind geoip2 returns a collection of names in all available languages for each field.
This PR allows us to change the language of a single result without having to reconfigure Geocoder.
=> Allow geoip2 result language to be changed for each result

README.md, lib/geocoder/cache.rb
A `NoMethodError` exception was raised when I tried expiring the cache while using a PORO Cache <-> DB adapter that did not implement `#keys`.
As an aside, sorry if it was inappropriate to submit the PR without creating an issue first, but it seemed unnecessary to create an issue for such a small change solely to documentation. I'm interested if you feel the same way, as I'm relatively new to contributing in the wild.
=> Add store#keys to Caching object requirements

lib/geocoder/results/opencagedata.rb, test/fixtures/opencagedata_madison_square_garden
Return the state_code instead of using state for state_code.
NOTE: OpenCage Data only supports state codes for certain countries, at the moment. See the list [here](https://github.com/OpenCageData/address-formatting/blob/master/conf/state_codes.yaml).
=> return state_code instead of alias state

lib/generators/geocoder/config/templates/initializer.rb
I noticed this option was in the README, but not in the template, so it
might be nice to have it generated in the template as well.
=> add ip_lookup option to initializer template

lib/geocoder/lookups/mapbox.rb, test/unit/lookups/mapbox_test.rb
The Mapbox  geocoding api supports additional parameters such as country. This PR enables geocoder to set these parameters for Mapbox lookups per query.
=> Add support for query params in mapbox lookup.

README.md, lib/tasks/geocoder.rake
That's a proposal to limit the objects that will be geocoded by the rake task, using an environment variable (LIMIT).
It could be useful if you want to geocode thousands of objects and don't want to reach the per-day limits of the geocoding services (for example if you are running the rake task in production and you are using the service for other porpoises.
It won't use batches when LIMIT is used, because _limit_ and _find_each_ don't work together.
Comments and/or corrections are very welcome :)
=> Allow to limit the objects that will be geocoded by rake task

README.md
It seems that pelias section had the same links as mapzen. Changed that so that it points to pelias github page.
=> Change documentation about pelias

lib/geocoder/lookups/base.rb
if you're behind a firewall, you'll get
Errno::ECONNRESET (Connection reset by peer - SSL_connect)
=> add connreset to network errors

geocoder.gemspec
Makes it easy to programatically find the source code and changelog for `geocoder`, using the rubygems API. More details on the direction of travel for gemspecs is [here](https://github.com/rubygems/rubygems.org/issues/1127) and [here](https://github.com/rubygems/rubygems.org/pull/1234), and the current state is [here](https://github.com/rubygems/rubygems/blob/master/lib/rubygems/specification.rb).
(My interest in this is so that [Dependabot](https://dependabot.com) can find a link to the `geocoder` source code when it creates PRs. Without that link, we generate PRs like [this one](https://github.com/greysteil/onebody/pull/8), rather than PRs like [this one](https://github.com/greysteil/onebody/pull/12).)
=> Add source code and changelog links to gemspec

lib/geocoder/results/nominatim.rb, test/fixtures/nominatim_cologne_cathedral_cologne_germany, test/unit/lookups/nominatim_test.rb
First of all, thanks a lot for this gem!
I've been using it for a while and recently switched to Nominatim. I noticed a few address parts were missing, namely:
- state_district
- neighbourhood
- city_district
Those are often present in Nominatim responses but not always, so I added a fixture and specs.
Thanks for checking!
=> add #city_district, #state_district, #neighbourhood to Nominatim response

lib/geocoder/results/opencagedata.rb, test/unit/lookups/opencagedata_test.rb
The OpenCage API [may include a time zone in the response](https://geocoder.opencagedata.com/api#annotations). This PR adds `#time_zone` to the `Opencagedata` result so it can be accessed when it's available.
`Geocoder::Result#time_zone` has been previously implemented in  [`Maxmind`](https://github.com/alexreisner/geocoder/blob/6589b9b2cd6d1cdda06bd1f598fe9ad070d8e5a9/lib/geocoder/results/maxmind.rb#L49) and [`Pointpin`](https://github.com/alexreisner/geocoder/blob/6589b9b2cd6d1cdda06bd1f598fe9ad070d8e5a9/lib/geocoder/results/pointpin.rb#L31) so hopefully it makes sense to add it to `Opencagedata` too.
=> Add time_zone to Opencagedata result

lib/geocoder/stores/active_record.rb, test/db/migrate/001_create_test_schema.rb, test/test_helper.rb, test/unit/near_test.rb
Related to #334 (Near search using column for radius) and #449 (Allow symbol to mean radius comes from a db column)
I decided to not change `.bounding_box` based on the reasons discussed on #449, but instead build the bounding box based on the maximum radius and simply "filter" the results based on the distance between the min_radius (defaults to 0.0) and whatever is stored in _radius_column_. The performance hit is dependent on how variable the radiuses stored in the DB are. 
Other concern discussed previously: **Security**. I haven't handled this one. But what I had in mind, was to compare the given `radius_column` to the model's column_names array: `Place.column_names.column_names.include?  radius_column.to_s`, but decided not to implement it until we discussed it further. 
I wasn't …
=> Allows radius to be a symbol representing a column in DB

README.md
Hi Alex,
Just a quick update now that OpenCage Geocoder is out of beta :-) Thanks!
Congrats on getting featured in [Ruby Weekly](http://rubyweekly.com/issues/363) by the way!
Alex
=> Update OpenCage Data README section

README.md
`Geocoder.coordinates('location')` properly sets the lat/lon coordinates for a given model, but returns `nil` when used in conjunction with testing stubs. 
This can be solved by adding a coordinates key to each stub. The latitude and longitude keys can then be removed, as they are no longer needed. 
No changes to the codebase were necessary, simply an update to the README to reflect this use.
#1197
=> Add coordinates for testing stubs to README

README.md
Geocoder.us seems to no longer exist so I eliminated it from the readme. Fixed one typo and updated pricing for geocod.io and smarty streets.
=> Services readme update

README.md
Support for additional query params was added with commit
844da1c11c2e74777ee8aab40cf82cee0f68dfa8 but this was not reflected in
the documentation.
=> Update docs to include additional Mapbox options

README.md
This updates the README section for Mapzen and Pelias. Fixes outdated rate limits, fills in the ?, and adds documentation and links to new pricing information for Mapzen, and also links for Pelias. 
Thanks!
(disclosure: I am a Mapzen employee.)
=> Update Mapzen and Pelias information in readme

.travis.yml, Gemfile, Rakefile, gemfiles/Gemfile.rails3.2, gemfiles/Gemfile.rails4.1, gemfiles/Gemfile.rails5.0
Closes #1224. There were a few main causes:
* bundler was missing on jruby-19mode in Travis CI's image so I slightly modified a suggested fix from here: https://github.com/travis-ci/travis-ci/issues/5578#issuecomment-180445244
* the `pg` gem released a new 1.0.0 version yesterday which caused issues with [Rails versions < 5 requiring `~> 0.11` at runtime](https://github.com/rails/rails/blob/0cad778c2605a5204a05a9f1dbd3344e39f248d8/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb#L13), and [Rails 5 requiring `~> 0.18`](https://github.com/rails/rails/blob/71f4758c50fca5220429365c23b014458e7341f6/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb#L2) (figuring this out was slightly complicated by ruby/rake#247)
* the `activerecord-jdbc-adapter` …
=> Fix Travis CI build errors. Closes #1224

lib/geocoder/lookups/bing.rb, test/fixtures/bing_forbidden_request, test/fixtures/bing_internal_server_error, test/unit/lookups/bing_test.rb
This attempts to fix https://github.com/alexreisner/geocoder/issues/841. 
Summary
=======
Bing returns the status codes within the json response. When a request is forbidden, it will return a 403. If there is an internal server error, it will return a 500. And if the service is unavailable for some other reason, it will return a 503. That information was obtained from bing's [Status Codes and Error Handling](https://msdn.microsoft.com/en-us/library/ff701703.aspx) documentation.
In this commit, we handle those three status codes by raising `Geocoder::RequestDenied` (for 403) and `Geocoder::ServiceUnavailable` (for 500 and 503). This allows for the users of the Geocoder to handle those errors in their applications.
I added two fixtures to the tests, one that returns a 403 and another that …
=> Raise bing errors for statuses 403, 500, 503

README.md, lib/geocoder/lookup.rb, lib/geocoder/lookups/ipdata_co.rb, lib/geocoder/results/ipdata_co.rb, test/fixtures/ipdata_co_74_200_247_59, test/fixtures/ipdata_co_8_8_8, test/fixtures/ipdata_co_no_results, test/test_helper.rb, test/unit/error_handling_test.rb, test/unit/lookup_test.rb, test/unit/lookups/ipdata_co_test.rb
Hello everybody!
Here's another ip->geolocation endpoint. Most of it is inspired ~copy&pasted~ by the freegeoip example.
Side notes:
1) I see a lot of deprecation warnings when in run `rake test`
2) There is a failing spec on the latest commit of the master branch: 
```
===============================================================================================================================================================================================
/home/robert/Development/Ruby/geocoder/test/unit/lookups/yandex_test.rb:29:in `test_yandex_query_url_contains_bbox'
26:       "Some Intersection",
27:       :bounds => [[40.0, -120.0], [39.0, -121.0]]
28:     ))
=> 29:     assert_match(/bbox=40.0+%2C-120.0+%7E39.0+%2C-121.0+/, url)
30:   end
31: end
Failure: …
```
=> Provide ipdata.co as a lookup

lib/geocoder/stores/active_record.rb
Rails 5.2 changed the receiver within a scope from `klass` to `relation`. With that, we no longer have private access to `Geocoder::Store::ActiveRecord#near_scope_options`, and so must make it public.
see: https://github.com/rails/rails/pull/29301
Closes: #1247
=> Make #near_scope_options public for Rails 5.2

README.md
20 was used as an example radius value in the README for near(), but it isn't explicitly mentioned that it's the default. I had to look through the code to find out, and found it here:
https://github.com/alexreisner/geocoder/blob/bab2e367880b02505dea077951bfada987e2c93d/lib/geocoder/stores/active_record.rb#L117
It would be nice if the README was clearer.
=> Explain that 20 is default radius for near()

lib/geocoder/results/google.rb, test/fixtures/google_new_york, test/unit/lookups/google_test.rb
some google geocoding requests have bounds within the result.  add a
helper to extract these.
=> add bounds detection for google results

lib/geocoder/lookups/geocodio.rb
Update to Geocodio API v1.3 (https://geocod.io/docs/#v1-3-released-on-march-12th-2018).
Always request additional `timezone` information (open to other ways to accomplish this, but see https://github.com/alexreisner/geocoder/issues/1273).
=> Update Geocodio to v1.3

lib/geocoder/lookups/telize.rb, test/fixtures/telize_74_200_247_59, test/unit/lookups/telize_test.rb
Telize is moving from their current "/geoip" endpoint to a new "/location" endpoint. [See the announcement here.](https://market.mashape.com/fcambus/telize/announcements/2)
The /geoip endpoint will stop receiving database updates as of May 1st, and will stop responding to queries as of June 1st, so it is important to get this updated quickly for all Telize users.
The new endpoint does return data in a slightly different format, as detailed here: https://www.telize.com/telize-2.0.0-has-been-released/
=> Use new /location endpoint for Telize

lib/geocoder/results/geoip2.rb
As requested and discussed on #1291, removing `data` method so we can access the `@data` variable made available on `Geocoder::Result::Base`.
Ran the specs locally and none started failing after the change (had one already failing before the change).
=> Remove Geocoder::Results::Geoip2#data

README.md, geocoder.gemspec, lib/generators/geocoder/config/templates/initializer.rb, lib/geocoder/lookup.rb, lib/geocoder/lookups/ipstack.rb, lib/geocoder/results/ipstack.rb, test/fixtures/freegeoip_74_200_247_59, test/fixtures/ipstack_134_201_250_155, test/fixtures/ipstack_access_restricted, test/fixtures/ipstack_batch_not_supported, test/fixtures/ipstack_inactive_user, test/fixtures/ipstack_invalid_access_key, test/fixtures/ipstack_invalid_api_function, test/fixtures/ipstack_invalid_fields, test/fixtures/ipstack_missing_access_key, test/fixtures/ipstack_not_found, test/fixtures/ipstack_protocol_access_restricted, test/fixtures/ipstack_too_many_ips, test/fixtures/ipstack_usage_limit, test/test_helper.rb, test/unit/lookup_test.rb, test/unit/lookups/ipstack_test.rb
Fixes #1279 
One of the unique problems here is that regardless of whether people update versions of this gem, the functionality for freegeoip will just stop.  We can introduce as many mechanisms in this PR to help with that, but there will probably be quite a few people for whom they wake up July 1st and their project just doesn't work.
The post install message contains a link to a wiki page (currently just empty) on how to upgrade from freegeoip to Ipstack. I have a draft of what the wiki page could contain on my forks wiki section [here](https://github.com/Heath101/geocoder/wiki/Freegeoip-Discontinuation-Upgrade-Instructions).  I would love as a part of reviewing this PR input on the content of that wiki page as well.  Then when it is ready we can replace the dummy one that I already …
=> Deprecate Freegeoip and Implement Ipstack

lib/geocoder/lookup.rb, lib/geocoder/lookups/postcodes_io.rb, lib/geocoder/results/postcodes_io.rb, test/fixtures/postcodes_io_malvern_hills, test/fixtures/postcodes_io_no_results, test/test_helper.rb, test/unit/lookup_test.rb, test/unit/lookups/postcodes_io_test.rb
This PR adds Postcodes.io lookup integration. Postcodes.io is an open source, freely available service for converting UK postcodes to location data. It is more up to date than others such as Google, and free, compared to PostcodeAnywhereUK, which isn't.
=> Postcodes.io lookup implementation

lib/geocoder/lookups/google.rb
When Google returns a geocoding error, there is often helpful debugging information in the error message which is currently silently swallowed, this adds that text to the error handling.
Use case: Our API key had referrer enforcement turned on, suddenly today Google cut off out server side API as not allowed, this was unexpected and all we got from the server was request denied, manually curling the api cause the correct details to be exposed:
```
{
"error_message" : "API keys with referer restrictions cannot be used with this API.",
"results" : [],
"status" : "REQUEST_DENIED"
}
```
=> Add error details

lib/geocoder/lookups/ipdata_co.rb, test/unit/lookups/ipdata_co_test.rb
Ipdata.co no longer accepts the API key as a header. It must be sent as a query parameter.
=> Fix Missing API Key for Ipdata.co Lookups

README_API_GUIDE.md
This is the new correct link to Nominatim Terms of Service policy page.
=> Update Nominatim Terms of Service policy link

README.md
I was using `ip_lookup` and I struggled to find this config when I was testing. 
I think this is useful for people that use `ip_lookup` in their apps.
=> Add ip_lookup to test instructions

README_API_GUIDE.md, lib/geocoder/lookups/ipinfo_io.rb, test/unit/lookups/ipinfo_io_test.rb
It appears that at some point they changed the "TLS only for paying
customers" rule.
See: https://ipinfo.io/developers#https-ssl
"Our API is available over a secure HTTPS connection for all users, even
on the free plan."
=> Allow https for IPInfo.io queries without an API key

lib/geocoder/lookups/pelias.rb, test/unit/lookups/pelias_test.rb
- Fixes #1353
- Do not limit the results returned from Pelias to 1;
- Removed test that was enforcing this condition;
=> Modify Pelias lookup to return multiple results

README_API_GUIDE.md, lib/geocoder/lookups/bing.rb, lib/geocoder/lookups/here.rb, test/unit/lookup_test.rb
Currently Geocoder doesn't allow us to pass language parameter to `bing` and `here` even though both API's support it.
Let me know is there is something else that needs to be changed.
=> Allow to pass language parameter for bing and here lookups

lib/geocoder/lookups/smarty_streets.rb
Fixed a small typo. It shows up when you don't pass SmartyStreets credentials, but doesn't seem to affect the actual geocoding.
=> Fixed typo

lib/geocoder/lookups/smarty_streets.rb, lib/geocoder/results/smarty_streets.rb, test/fixtures/smarty_streets_13_rue_yves_toudic_75010, test/unit/lookups/smarty_streets_test.rb
Hi, thanks for this great project 👍 This PR adds support for the SmartyStreets [International API](https://smartystreets.com/docs/cloud/international-street-api).
The international endpoint will be used if the user passes a country, which is a required parameter for it.
```ruby
Geocoder.search(address, country: "France")
```
=> Support for SmartyStreets International API

lib/geocoder/lookups/base.rb
When a response can't be parsed it would be nice to be able to see the details when running in debug mode rather than receiving a warning of the full response body as this can be lengthy and uninformative and cause unnecessary noise in production system logs.
=> Suggestion to not log full response body as a warning

README_API_GUIDE.md, lib/geocoder/lookups/here.rb, test/unit/lookups/here_test.rb
Currently Geocoder uses an old version of the `here` API. This change updates the API version and allows the support of country and mapview parameters.
=> Add country and mapview as extra parameters to here lookup

README_API_GUIDE.md
Realized I put "SSL support: no" when the API only supports HTTPS.
=> update faulty Tencent SSL information in API Guide

lib/geocoder/lookups/freegeoip.rb, test/unit/lookups/freegeoip_test.rb
Since freegeoip was deprecated a similar service called freegeoip.app provides the same results, the only thing mandatory is to use `https`
This PR makes adjustments to work with `:freegeoip` as before without changes for the end user
I was thinking about creating a new API provider but since freegeoip is deprecated, simply modifying it could bring it to life again
The same can be achieved without this PR, using:
```
Geocoder.configure(
ip_lookup: :freegeoip,
freegeoip: { host: "freegeoip.app" },
use_https: true
)
```
=> Add adjustment to freegeoip to use freegeoip.app

lib/geocoder/lookups/yandex.rb
https://tech.yandex.ru/maps/doc/geocoder/desc/concepts/input_params-docpage/
=> Correct param name for api key is "apikey"

lib/geocoder/results/here.rb
This pull request fixes a bug with mapping for `Here` as `state` was mapped to `county`.
=> Fix here mapping for state and add state_code

lib/geocoder/lookups/yandex.rb
The **plng** parameter didn't change the response language in yandex. Look this: 
https://tech.yandex.com/maps/geocoder/doc/desc/concepts/input_params-docpage/
With the **lang** parameter we fix the problem
=> fix yandex language param

lib/hash_recursive_merge.rb
`o` variable in the `HashRecursiveMerge#rmerge` method definition is not necessary in the result hash calculation
=> Remove unnecessary variable

README_API_GUIDE.md
Seems like with https://github.com/alexreisner/geocoder/issues/1429 and https://github.com/alexreisner/geocoder/pull/1430, the API key for HERE integration should now be provided like so:
```
Geocoder.configure(api_key:  "my api key")
```
The API key is displayed in HERE Project Page as documented here: https://developer.here.com/documentation/authentication/dev_guide/topics/api-key-credentials.html
=> Remove bad information from HERE API docs

lib/geocoder/results/yandex.rb, test/unit/lookups/yandex_test.rb
We should use one of these, cause geocoding results are different.
I add one commit with failing tests and another commit with a fix
I can't get `street` and `street_number` for such geocoding result:
```
#<Geocoder::Result::Yandex:0x00007f7fcce5f288
@data={
"GeoObject"=>{
"metaDataProperty"=>{
"GeocoderMetaData"=>{
"precision"=>"exact",
"text"=>"Россия, Воронеж, Ленинский проспект, 184Б",
"kind"=>"house",
"Address"=>{
"country_code"=>"RU",
"formatted"=>"Россия, Воронеж, Ленинский проспект, 184Б",
"postal_code"=>"394021",
"Components"=>[
{"kind"=>"country", "name"=>"Россия"},
{"kind"=>"province", "name"=>"Центральный федеральный округ"},
{"kind"=>"province", "name"=>"Воронежская область"},
{"kind"=>"area", "name"=>"городской округ Воронеж"},
{"kind"=>"locality", "name"=>"Воронеж"}, …
```
=> [Yandex] Wrong condition for locality data

lib/geocoder/lookups/latlon.rb
lib/geocoder/lookups/latlon.rb:28: warning: `elsif' at the end of line without an expression
=> [fix] ruby 2.7.1 warning

lib/geocoder/ip_address.rb, test/unit/ip_address_test.rb
Resolves issue where trying to search via an IP address with a port was not working properly
Example:
`Geocoder.search("[3ffe:0b00:000:0000:0001:0000:0000:000a]:80")`
Resolves https://github.com/alexreisner/geocoder/issues/1396
=> Support IP search with port

lib/geocoder/lookups/yandex.rb
Yandex response has changed. 
There was param named "found" before. But it was removed. So any geocode request returned empty array.
Actually i consider the condition as redundant.
=> Yandex fix. No more "found" param in meta section

README_API_GUIDE.md, lib/geocoder/lookups/telize.rb, test/unit/lookup_test.rb, test/unit/lookups/telize_test.rb
The Mashape API proxy has been deprecated and needs to be replaced with RapidAPI proxy URL to work reliably.
=> Update from Mashape to RapidAPI

lib/geocoder/results/db_ip_com.rb, test/fixtures/db_ip_com_madison_square_garden, test/unit/lookups/db_ip_com_test.rb
Currently, the `state_code` method on a result from db-ip.com returns the full state name. But the data returned from their API actually does include a 2 character state code, under `stateProvCode`.
Here is a sample query that I just performed:
```irb
irb(main):005:0> results = Geocoder.search("96.27.101.109")
irb(main):006:0> results[0].state_code
=> "Ohio"
irb(main):007:0> results[0].data['stateProvCode']
=> "OH"
```
=> Support state_code in results from db-ip.com

lib/geocoder/lookups/google.rb, lib/geocoder/lookups/google_places_details.rb, lib/geocoder/lookups/google_places_search.rb, lib/geocoder/lookups/google_premier.rb, test/fixtures/google_places_search_madison_square_garden, test/unit/lookups/google_places_search_test.rb
=> Control Google places search API price

lib/geocoder/results/nationaal_georegister_nl.rb, test/unit/lookups/nationaal_georegister_nl_test.rb
The coordinates are returned in a specific notation from the NationaalRegisterNl API:
`POINT(4.89133064 52.3739109)`
The result class parses that so we get 2 individual coordinates. But the gem expects it in this format `[latitude, longitude]`. The result class returned `[longitude, latitude]`. So if you'd use this with the `geocode` method you would get the coordinates saved in the wrong attribute. Therefor I reversed the array. 
Confirmation that the coordinates in the fixture and test are now correct (or close enough ;)):
https://www.coordinatenbepalen.nl/coordinates/144787-nieuwezijds-voorburgwal-147-1012rj-amsterdam
=> Reverse coordinates when parsing from NationaalregisterNl

README.md, lib/geocoder/lookups/test.rb, test/unit/test_mode_test.rb
Hope this is a welcome possibility. I've got a test suite where folks want more fine-grained cleanup in their tests:
```ruby
before(:all) do
Geocoder::Lookup::Test.add_stub(
"New York City, NY", [
{  'coordinates'  => [40.7143528, -74.0059731] }
]
)
end
after(:all) do
Geocoder::Lookup::Test.delete_stub('New York City, NY')
end
```
We didn't want to `reset` because the default stub doesn't need to change across the suite.
I took a stab at a name (`delete`, versus the word `reset` you use elsewhere, or maybe a more generic `remove`). Happy to take feedback. The unit test is also a _little_ indirect, but I think it covers the case?
=> Allow single stubs to be removed in test mode

lib/geocoder/lookups/maxmind_local.rb
Hey @alexreisner, thanks for this great gem and keeping it up-to-date for 11+ years!
This PR allows the `file` and `package` options to be used together, which allows Geocoder to work with the `geoip-database` Ubuntu package (useful for platforms like [Heroku](https://devcenter.heroku.com/articles/stack-packages)).
```ruby
Geocoder.configure(
ip_lookup: :maxmind_local,
maxmind_local: {
file: "/usr/share/GeoIP/GeoIP.dat",
package: :country
}
)
```
Otherwise, lookups fail with:
```text
UncaughtThrowError (uncaught throw "Invalid GeoIP database type, can't look up City by IP")
```
I didn't see any tests for the `file` option, so it's just been tested manually.
=> Adds support for country file lookup to MaxMind Local

lib/geocoder/results/ban_data_gouv_fr.rb, test/fixtures/ban_data_gouv_fr_montpellier, test/unit/lookups/ban_data_gouv_fr_test.rb
We have `region_name`, but unfortunately we don't have `region_code`. When storing regions in a database I feel like it's much better to store a technical code rather than a name, it can be error prone especially because of different ways to write it (french is weird).
Unfortunately the ban_data_gouv API does not provide with the region code, only its name.
I used the [region API](https://geo.api.gouv.fr/decoupage-administratif/regions) to get a hard-coded list of regions and their code and use it as lookup.
Those region names and code should not change so often so I figure this is an OK way to solve the problem, I don't think making an API call to get the region code would be advised, maybe if hardcoding the codes is a no-go, we could memoize or cache the API result so we only make one …
=> Improve ban_data_gouv_fr result

README_API_GUIDE.md, lib/geocoder/lookup.rb, lib/geocoder/lookups/abstract_api.rb, lib/geocoder/results/abstract_api.rb, test/fixtures/abstract_api, test/fixtures/abstract_api_2_19_128_50, test/test_helper.rb, test/unit/lookup_test.rb, test/unit/lookups/abstract_api_test.rb
Integration of one of my favorite API in one of my favorite Gems :)
BTW, after this PR, I am thinking of integrating a linter like Rubocop in Geocoder. What do you say?
=> Abstract API

README.md
Hi folks! 👋 
The documentation section on contributing was moved to a separate file in https://github.com/alexreisner/geocoder/commit/a81e028cf21d1fd31f3990ed22c466962f138a21, but the link in the main README still used anchors to the README itself for both the 'Contributing' and 'Reporting Issues' links.
This updates those links so they point to the contributing file on GitHub. Even though it's now a small document, both links point to the heading for the relevant section using anchors.
=> Fix link to CONTRIBUTING.md in README

README_API_GUIDE.md
Some of the links in the Pelias documentation are not up to date.
This updates them to refer to the up to date documentation available at:
https://github.com/pelias/documentation
This also adds information about a couple of service providers for managed instances I found. There doesn't seem to be any references available to any other service providers than the "official" one (Geocode Earth). I just accidentally noticed Geoapify is also providing such service when implementing #1462 (their cloud service is not Pelias compatible but they provide managed Pelias as a separate service). I think these deserve to be listed somewhere for easier discovery.
=> Update Pelias documentation

lib/geocoder/lookups/uk_ordnance_survey_names.rb, test/fixtures/uk_ordnance_survey_names_SW1A1AA, test/fixtures/uk_ordnance_survey_names_london, test/fixtures/uk_ordnance_survey_names_no_results
The Ordnance Survey API have launched [OS Data Hub](https://osdatahub.os.uk/). As part of this, users are being pushed to migrate their use to the Data Hub **before 31 May,** which uses a new API endpoint. 
This PR allows the gem to support the new endpoint alongside the existing one. I'm not sure what will happen to the existing endpoint come 31 May, but for now this will allow those who use this gem and wish to migrate to do just that.
They say that the functionality of their API hasn't changed at all. (see screenshot)
=> Add support for the new OS Data Hub to uk_ordnance_survey_names lookup

lib/geocoder/results/esri.rb, test/fixtures/esri_austin_tx, test/fixtures/esri_madison_square_garden, test/fixtures/esri_new_york_ny, test/fixtures/esri_washington_dc, test/unit/lookups/esri_test.rb
Not sure if this is a newer addition to the Esri API, but this PR maps `state_code` to the region abbreviation field, and defaults it back to the old implementation of `state` if it's nil or empty. 
Here's an example of Esri location data
```
irb(main):001:0> Geocoder.config.lookup #=> :esri
irb(main):002:0> pp Geocoder.search('Portland, OR').first.data['locations'].first
{"name"=>"Portland, Oregon",
"extent"=>
{"xmin"=>-122.82162999999996,
"ymin"=>45.365790000000075,
"xmax"=>-122.52962999999995,
"ymax"=>45.65779000000008},
"feature"=>
{"geometry"=>{"x"=>-122.67562999999996, "y"=>45.511790000000076},
"attributes"=>
{"Loc_name"=>"World",
"Status"=>"M",
"Score"=>100,
"Match_addr"=>"Portland, Oregon",
"LongLabel"=>"Portland, OR, USA",
"ShortLabel"=>"Portland",
"Addr_type"=>"Locality", …
```
=> Adjust state_code for Esri lookups

lib/geocoder/lookups/geoip2.rb
Adds a configuration option to use the local_ip_alias attribute of the maxminddb library to use a local IP address to geolocate during testing. I don't use the Hive::GeoIP2 gem to test it with but the configuration option will only work if the class responds to the attribute so it shouldn't fail if it doesn't exist.
=> feat: add configuration option for maxminddb local_ip_alias

lib/geocoder/lookups/ip2location.rb, test/unit/lookups/ip2location_test.rb
Just a little PR to update the `ip2location` lookup to use [their v2 API](https://www.ip2location.com/web-service/ip2location).
=> Update ip2location lookup for v2 API

lib/geocoder/ip_address.rb, test/unit/ip_address_test.rb
If using `geocoded_by` with an ActiveRecord column with an `inet` type the value is automatically converted to an `IPAddr`. This then prevents geocoder from recognizing it as an IP, as it expects a string.
This updates the `IpAddress` initializer to accept  and convert an `IPAddr`.
=> Accept IPAddr when initializing an IpAddress

lib/geocoder/lookups/bing.rb, test/unit/lookup_test.rb
As you can check documentation https://docs.microsoft.com/en-us/bingmaps/rest-services/common-parameters-and-types/culture-parameter for response in proper language you should add culture param instead language
=> Proper language param for bing maps.

lib/geocoder/lookups/ipqualityscore.rb, test/fixtures/ipqualityscore_insufficient_credits, test/fixtures/ipqualityscore_quota_exceeded, test/unit/lookups/ipqualityscore_test.rb
A small update to improve the over-quota handling for IPQualityScore geocoding lookups.
=> Improve ipqualityscore OverQueryLimitError detection

lib/geocoder/lookups/ipqualityscore.rb, test/unit/lookups/ipqualityscore_test.rb
Hey @alexreisner, another small IPQualityScore fix for you; this one ensures that only successful responses are cached, when caching is enabled.
=> IPQualityScore unsuccessful response caching fix

test/unit/lookups/geocodio_test.rb
I made a copy of these tests to start which is how I introduced the typo here: https://github.com/alexreisner/geocoder/pull/1521#discussion_r695942405
So I figured I'd remove it from this file so no one else makes the same copy-pasta mistake
=> Remove duplicate Geocoder.configure

lib/generators/geocoder/config/templates/initializer.rb, lib/geocoder/cache.rb, lib/geocoder/cache_stores/base.rb, lib/geocoder/cache_stores/generic.rb, lib/geocoder/cache_stores/other.rb, lib/geocoder/cache_stores/redis.rb, lib/geocoder/configuration.rb, lib/geocoder/lookups/base.rb
Applying open for extensions principle
and Adding support for redis expiration (ttl)
usage:
```ruby
Geocoder.configure(
lookup: :google,
api_key: ENV['GMAPS_PLAECS_KEY'].try(:freeze),
cache: Redis.current,
cache_prefix: "GeocoderCache:",
expire: 2.days
)
```
=> Open for extensions + redis expiration

lib/geocoder/lookups/ipdata_co.rb
ipdata introduced an EU endpoint for API calls. https://docs.ipdata.co/
This pull request adds support for passing host parameter to ipdata_co lookup.
=> add support for host parameter to ipdata_co lookup

lib/geocoder/lookups/amazon_location_service.rb
aws-sdk-locationservice raises and error when :lookup parameter is given:
```ArgumentError: unexpected value at params[:lookup]```
This Pr fixes this and improves readability
=> ArgumentError: unexpected value at params[:lookup]

test/test_helper.rb, test/unit/lookups/amazon_location_service_test.rb
closes #1552
index_name is required parameter. See: https://github.com/aws/aws-sdk-ruby/blob/9557e95a0b72a3c324e81443237745d9b6e3f3e8/gems/aws-sdk-locationservice/lib/aws-sdk-locationservice/client.rb#L2880
https://github.com/aws/aws-sdk-ruby/blob/9557e95a0b72a3c324e81443237745d9b6e3f3e8/gems/aws-sdk-locationservice/lib/aws-sdk-locationservice/client.rb#L3155
existing test didn't reflect this
This PR fixes this.
=> fix: unknown keyword: :index_name

lib/geocoder/results/nominatim.rb
To mitigate the issues reported in https://github.com/alexreisner/geocoder/issues/1556
I've moved the direct lookup of `address` within `@data` to a new private method `#address_data` that always returns a Hash if the result is nil, allowing the lookup methods to return nil instead of an error.
Also the `#coordinates` method now returns an empty array, which will be picked up by `#geocoded?` as false:
```ruby
module Geocoder
module Store
module Base
##
#
def geocoded?
to_coordinates.compact.size == 2
end
end
end
end
```
I choose the `#address_data` method name as the `#address` method is already used within other result objects as a public method.
I was unable to run the test suite on my M1, so that still needs some checking.
=> #1556 Made the Nominatim parsing more robust

README.md
After upgrading we noticed that the configuration we had set originally resulted in a crash (which worked on version 1.6.3 but not after updating to 1.7.2):
```
Geocoder.configure(cache: Rails.cache)
ArgumentError: wrong number of arguments (given 1, expected 0)
from <abbreviated>/gems/activesupport-5.2.6/lib/active_support/cache/redis_cache_store.rb:166:in `initialize'
```
Initially I wrote a simple adapter around `Rails.cache` but when I was preparing a PR I noticed that we could use the Generic cache store wrapper to work with `Rails.cache`.
This PR helps the developer who uses `Rails.cache` to setup Geocoder's caching functionality.
It also instructs the developer to use the non deprecated way of setting the cache prefix as it was moved.
This was the adapter I initially wrote:
```ruby …
```
=> Update documentation with instructions for Rails.cache

lib/geocoder/configuration.rb
When using the Gem on version 1.7.2, i've noticed that when using the cache option it will by default spit out a deprecation warning to not use the configuration option: `cache_prefix` anymore.
```
[Geocoder] cache_prefix is deprecated, please change to cache_options.prefix instead
```
This PR moves the default value for `cache_prefix` to its new desired location so that the deprecation warning will be removed when a developer is not explicitly setting the incorrect option.
See my other PR for a documentation change in the README.md to use the correct location
=> Move cache_prefix config option to cache_options

lib/geocoder/lookups/freegeoip.rb
The `Lookup::Base` class [recommends](https://github.com/alexreisner/geocoder/blob/31153d518687351b68a5d0abd5e087f47e6f4204/lib/geocoder/lookups/base.rb#L74-L76) that implementations _not_ override the `query_url` method, but instead provide `base_query_url` and `url_query_string` methods. This PR brings the Freegeoip provider inline with that recommendation.
This was necessary in order to add support for an `apikey` parameter, required by some services such as freegeoip.app.
=> Freegeoip abides by base class recommendations and supports an api key

README_API_GUIDE.md, lib/geocoder/lookups/location_iq.rb
I have no affiliation with LocationIQ besides as a user.
However, per an email received recently, the endpoint used by this gem is being deprecated.
Details below...
```
Hello,
We’re pushing a few changes to ensure continued service, higher availability, and lower latencies for our APIs.
What’s changing?
On 1st June 2022 at 00:00 UTC, we’re going to deprecate some endpoints used to reach our Geocoding, Routing & Timezones APIs. These include older & root domain endpoints such as [us1.locationiq.org/v1](http://us1.locationiq.org/v1), [eu1.locationiq.org/v1](http://eu1.locationiq.org/v1), [locationiq.org/v1](http://locationiq.org/v1), and [locationiq.com/v1](http://locationiq.com/v1).
Starting 1st June, our Geocoding, Routing & Timezone APIs will only respond to requests sent to these two …
```
=> Update LocationIQ Endpoint

examples/extend_lookup_services.rb, lib/geocoder/lookup.rb
This will allow for extending Geocoder with additional lookups that come from the application, not shipped with the gem. 
```ruby
module Geocoder::Lookup
class MyPreciousss < Google
end
end
Geocoder::Lookup.street_services << :my_preciousss
Geocoder::Lookup.street_services << :my_other
```
An example use case for this is, when we have several groups of users in the application, or tenants who use Google paid services and we want to properly separate these paid services. Since Geocoder Configuration is a `Singleton`, we cannot do this by creating an "instance" of the Geocoder with different api_key(s). As a workaround, you can define Google Lookup subclasses and define a different api_key for each of them.
The main problem I am trying to solve here is that you cannot define different …
=> Only require Lookup classes if not defined to allow lookup extensions

lib/geocoder/lookup.rb
This will prevent name collisions with modules or classes with the same name as classes in Lookup in the development environment where code is not eager loaded. However, this introduces an additional limitation for additional Lookup classes defined by the gem users, they must be defined in the namespace `Geocoder::Lookup`.
Resolves:  https://github.com/alexreisner/geocoder/issues/1568
Missing a proper test where we could reproduce the name collision.
=> Avoid name collision by const_get only lookups from Geocoder::Lookup

README.md, lib/geocoder/configuration.rb, test/unit/geocoder_test.rb
Hi there, 
Thanks for the awesome work on the Geocoder gem! We noticed there isn't a default TTL for any cache key after we saw our Redis instances get filled up with cached Geocoder lookup calls.
Based on the current documentation, I would have expected a default TTL of two days. However, that's not the case. To make sure others won't have the same issue, I thought it would make sense to add a default TTL for every key of two days. 
Looking forward to any feedback.
=> Add a default TTL when caching

README_API_GUIDE.md, lib/geocoder/lookups/google_places_search.rb, test/unit/lookups/google_places_search_test.rb
Hi again! I needed to add the `locationbias` parameter for my work and figured other users could maybe take advantage of it too. This PR adds a simple form of support for `locationbias` to the `:google_places_search` lookup.
It can be specified in either the query options or configuration. If both, query takes precedence. A `nil` in the query options overrides a configured value, to omit `locationbias` from the API call, in a similar manner to #1572.
The way I've written it, it only takes a string, e.g. `"point:-36.8509,174.7645"`, which is just passed directly to the API call. I thought about being more sophisticated, _e.g._, getting it to take a hash of the form `{point: [-36.8509, 174.7645]}` instead. But my thinking on this right now is:
- Google Places Search supports four different …
=> Add locationbias parameter to Google Places Search

lib/geocoder/lookups/yandex.rb
json response does not contain an error object anymore
https://yandex.ru/dev/maps/geocoder/doc/desc/reference/error_codes.html
=> Update yandex lookup error handling

test/test_helper.rb
I confess that I don't have a lot of experience using Test Unit in Ruby - I've mostly used Rspec. For a while now I've been making changes and running all the tests with this:
```
$ bundle exec rake test
```
But I finally decided to stop being lazy and learn something about Test Unit - I discovered I could run an individual test like so:
```
$ ruby -I test path/to/file.rb
```
This really helped me make some progress on the stuff I'm trying to add to this library but then I discovered that I'm able to run tests in isolation that succeed in the full suite - test leakage!!
Here's an example:
```
$ ruby -I test test/unit/lookups/maxmind_geoip2_test.rb
```
<details>
<summary>test/unit/lookups/maxmind_geoip2_test.rb</summary>
```
Loaded suite test/unit/lookups/maxmind_geoip2_test
Started
.E …
```
=> [dont merge] Configure tests with random order

README_API_GUIDE.md, lib/geocoder/lookups/geoapify.rb, test/unit/lookups/geoapify_test.rb
Geoapify has an [autocomplete api](https://www.geoapify.com/address-autocomplete)
This PR allows to use either the search or autocomplete API
=> Allow geoapify lookup to perform autocomplete query

lib/geocoder/lookup.rb, test/test_helper.rb, test/unit/lookup_test.rb
Related issue here: https://github.com/alexreisner/geocoder/issues/1568
It was marked as close and resolved, but I'm still seeing the same problem. I was able to recreate the bug on ruby `2.6.3` and geocoder version `1.8.0` with the following
```
require 'geocoder'
module Google
end
Geocoder.configure(:api_key => "YOUR-KEY", :lookup => :google)
Geocoder.search("Something")
```
Results in
```
Traceback (most recent call last):
6: from test.rb:7:in `<main>'
5: from /Users/avramtwitchell/.rvm/gems/ruby-2.6.3/gems/geocoder-1.8.0/lib/geocoder.rb:22:in `search'
4: from /Users/avramtwitchell/.rvm/gems/ruby-2.6.3/gems/geocoder-1.8.0/lib/geocoder/query.rb:11:in `execute'
3: from /Users/avramtwitchell/.rvm/gems/ruby-2.6.3/gems/geocoder-1.8.0/lib/geocoder/query.rb:40:in `lookup'
2: from …
```
=> existing constant name shadowing a lookup class name results in NoMethodError

lib/geocoder/ip_address.rb
Resolves the deprecation warning when supplying a hash to Geocoder.search.
Search checks whether the supplied search is_ipaddress? which in turn goes to the below function and displays the warning
`/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/geocoder-1.8.1/lib/geocoder/ip_address.rb:13: warning: Using the last argument as keyword parameters is deprecated`
i.e.
`Geocoder.search({ :city=>"Victoria" })`
=> Rails geocoder - Deprecation Warning

lib/maxmind_database.rb, lib/tasks/maxmind.rake
MaxMind changed how you download the GeoLite2 archives and now requires a valid license key. The data is still free there is just an additional step in the process. This pull request changes the download urls.
=> New maxmind download

lib/geocoder/cache.rb
Based on [this](https://github.com/alexreisner/geocoder/commit/4b9d2c689e8cacb6ce71714a7271bdb0952761cd) conversation, I think we should disable inheritance lookup behaviour for `get_const` method
=> Disable inherit flag const_get in `Geocoder::Cache#initialize`

lib/geocoder/lookups/amazon_location_service.rb
- Include region on Aws::LocationService::Client config
- Remove region key when is nil 
To avoid setup region via ENV vars while its using the keys approach
=> Feature: Include region on AWS lookup client config

lib/geocoder/lookups/esri.rb
Updated error handing for the `results` method in `lookups/esri.rb`
More inline with other geocoding `results` methods - see here: https://github.com/alexreisner/geocoder/blob/1928f7886823d63e0268eebd693ee20314ebdb08/lib/geocoder/lookups/bing.rb#L36
Before when ESRI would fail on a geocode (an example would be an invalid api key) Geocoder would return an empty array instead of an exception. 
Attached issue - https://github.com/alexreisner/geocoder/issues/1610
=> Updated esri lookups error handling

README_API_GUIDE.md, lib/geocoder/lookups/ban_data_gouv_fr.rb, lib/geocoder/results/ban_data_gouv_fr.rb, test/fixtures/ban_data_gouv_fr_montpellier, test/fixtures/ban_data_gouv_fr_paris, test/unit/lookups/ban_data_gouv_fr_test.rb
Updates for the ban_data_gouv_fr lookup : 
- Remove the old `village`, `town` and `city` (result) types which are no longer used
- Add the new `municipality` type (replacing old types)
- Update API Guide urls
Doc : https://adresse.data.gouv.fr/api-doc/adresse
=> Fix : param type in ban_data_gouv_fr lookup

lib/geocoder/lookups/pc_miler.rb, lib/geocoder/results/pc_miler.rb, test/fixtures/pc_miler_duluth_mn, test/fixtures/pc_miler_madison_square_garden, test/fixtures/pc_miler_reverse, test/fixtures/pc_miler_times_square, test/fixtures/pc_miler_wall_drug, test/unit/lookups/pc_miler_test.rb
To add useful metadata to the response data for Trimble maps single search integration we need to add the
[`include` url parameter with value 'Meta'](https://developer.trimblemaps.com/restful-apis/location/single-search/single-search-api/).
This PR takes care of such addition.
example call
``` https://singlesearch.alk.com/na/api/search?authToken=<TOKEN>&include=Meta&query=Feasterville Trevose, Pennsylvania 19053, United States```
response:
```{
"Err": 0,
"ErrString": "OK",
"QueryConfidence": 1,
"TimeInMilliseconds": 125,
"GridDataVersion": "GRD_ALK.NA.2023.01.18.29.1.1",
"CommitID": "pcmws-22.08.11.0-1778-g586da49bd1b: 05/30/2023 20:14",
"Locations": [
{
"Address": {
"StreetAddress": "",
"LocalArea": "",
"City": "Feasterville Trevose",
"State": "PA",
"StateName": "Pennsylvania",
"Zip": …
```
=> request metadata in Trimble maps single search call

lib/geocoder/lookups/pc_miler.rb, test/unit/lookups/pc_miler_test.rb
Remove double encoding because `hash_to_query` already does this in the base class.
=> Remove double encoding

lib/geocoder/lookups/google_places_search.rb, test/unit/lookups/google_places_search_test.rb
Removes legacy `id` and `reference` fields from Google Places Search results.
Closes #1627.
=> Remove references to legacy Google Places Search fields

geocoder.gemspec
Fix https://github.com/alexreisner/geocoder/issues/1642
=> Fix dependency warning in Ruby 3.3 and prepare for Ruby 3.4

lib/geocoder/lookups/amazon_location_service.rb, lib/geocoder/results/amazon_location_service.rb, test/fixtures/amazon_location_service_madison_square_garden, test/test_helper.rb, test/unit/result_test.rb
Place_id is a really useful unique location identifier. Since at least 2 of Amazon Location Service's place providers return this attribute, we would like to return it as a an attribute in the geocoder response as well.
=> Add place_id as a result attribute from amazon_location_service

lib/geocoder/results/mapbox.rb
Fixes `nil` return in the following `Geocoder::Result::Mapbox` methods: `city`, `state`, `state_code`, `postal_code`, `country`, `country_code`, and `neighborhood`. 
Given the following example of a "region" type response, the `Geocoder::Result::Mapbox` class will not return a value for the `state` or `state_code` methods despite the necessary data existing in the payload: 
```json
{
"id": "region.107756",
"type": "Feature",
"place_type": [
"region"
],
"relevance": 1,
"properties": {
"mapbox_id": "dXJuOm1ieHBsYzpBYVRz",
"wikidata": "Q1384",
"short_code": "US-NY"
},
"text": "New York",
"place_name": "New York, United States",
"bbox": [
-79.8046875,
40.4771401,
-71.763627,
45.0239467
],
"center": [
-75.4652471468304,
42.751210955038
],
"geometry": {
"type": "Point",
"coordinates": [ …
```
=> Fix nil values in mapbox result

lib/geocoder/results/mapbox.rb, test/fixtures/mapbox_chicago_il, test/fixtures/mapbox_chicago_il_60647, test/fixtures/mapbox_illinois, test/fixtures/mapbox_logan_square_chicago_il, test/fixtures/mapbox_united_states, test/unit/lookups/mapbox_test.rb
Follow up to https://github.com/alexreisner/geocoder/pull/1655
Non-nil values are now being returned (when appropriate) for the `city`, `state`, `state_code`, `postal_code`, `country`, `country_code`, and `neighborhood` methods. However, as a result the `Geocoder::Result::Mapbox#address` method needs to be updated otherwise the returned value will contain duplicated text. 
Example: Given that the `city` method now returns a value for "place" type results, a search result for "Chicago, IL" will return "Chicago, Chicago, Illinois, United States". This is because `.place_name` and `.city` return the same value, and both are being used to build the address. 
To solve this, we can simply use the `place_name` property on the Mapbox payload as the address rather than building our own. 
Specs and …
=> Update mapbox result to use place_name as address

README.md
@alexreisner I would like to hear your input about this, this is very optional addtition to the reademe file that might be helpful for some users
=> Update `README.md` file, use DB as storage

lib/geocoder/lookups/amazon_location_service.rb
This change will use `language` option from the config. Example: 
`language: :en`
Before this PR:
```
label = "ทางหลวงชนบทภก. 4018 ตำบลเชิงทะเล อำเภอถลาง จังหวัดภูเก็ต 83110",
municipality = "ตำบลเชิงทะเล",
postal_code = "83110",
region = "จังหวัดภูเก็ต",
sub_region = "อำเภอถลาง",
```
after:
```
label = "Phuket 4018 Rural Rd, Choeng Thale, Thalang, Phuket 83110, THA",
municipality = "Choeng Thale",
postal_code = "83110",
region = "Phuket",
sub_region = "Thalang",
```
=> Add Language support for AWS Locations service

lib/geocoder/lookups/bing.rb, lib/geocoder/lookups/mapbox.rb, test/unit/lookups/bing_test.rb, test/unit/lookups/mapbox_test.rb
=> Fix spaces in a url being encoded as '+' instead of '%20'

lib/geocoder/query.rb, test/unit/query_test.rb
=> Fixed NoMethod error when querying with an instance of IPAddr

lib/geocoder/lookups/mapbox.rb, test/unit/lookups/mapbox_test.rb
This PR fix the open bug issue https://github.com/alexreisner/geocoder/issues/1657 .
If geocoder is configured with MapBox and invalid api key and `always_raise` doesn't contain `Geocoder::InvalidApiKey`, `Geocoder.search` will throw the following error.
```
/usr/local/bundle/gems/geocoder-1.8.3/lib/geocoder/lookups/base.rb:46:in `search': undefined method `map' for false:FalseClass (NoMethodError)
results(query).map{ |r|
^^^^
Did you mean?  tap
```
`results(query)` is evaluated as `false` in https://github.com/alexreisner/geocoder/blob/5b379a5f626bcd6b2e932627996ef6ba22761afc/lib/geocoder/lookups/base.rb#L46
because `raise_error` is called in the `results` method, and `results` returns `false` if `always_raise` doesn't contain the argument error.
=> bug: Fixed unexpected error with invalid api key when exception-raising is not configured

lib/geocoder/results/mapbox.rb, test/unit/lookups/mapbox_test.rb
Fixes #1661
<strike>I was not able to easily get the tests up and running but it looks like `test/fixtures/mapbox_chicago_il` has what is needed to verify the new behavior because it should return "Chicago, Illinois, United States" after this change, wheras before the change it will return "Chicago"</strike>
(I was able to get the single test file running but did not run the full suite, but it looks like I was able to get it to go green in all the relevant places)
=> Return data['place_name'] for Geocoder:Result::Mapbox#place_name

lib/geocoder/stores/active_record.rb, test/unit/near_test.rb
With older Rails versions and Geocoder you could do something like:
```ruby
Person.near(city.coordinates, :"COALESCE(distance_preference, 100)")
Person.near(city.coordinates, :"CASE WHEN travels_by_foot THEN foot_travel_distance ELSE car_travel_distance END")
```
But with newer Rails versions (well, by newer I mean like 6.1 or something) the query ends up looking like
```sql
SELECT MAX("COALESCE(distance_preference, 100)") FROM people
```
(there's no column `"COALESCE(distance_preference, 100)"`)
So usually within Rails you would do `Person.maximum(Arel("COALESCE(distance_preference, 100)"))`
But with Geocoder due to the `radius.is_a?(Symbol)` check it's not possible,
so with this PR I am extending the logic to work with Arel SQL literals.
After this change the following code works: …
=> Radius column can be an instance of Arel.sql

README_API_GUIDE.md
source: https://adresse.data.gouv.fr/outils/api-doc/adresse
> Si le script sollicite l'API de géocodage sans précaution particulière, avec une fréquence qui dépasse la limite d'usage de 50 requêtes par seconde et par IP, alors :
>
> Les 50 premiers appels sont traités normalement ;
Le 51ème appel et les suivants sont bloqués tant que le script continue à solliciter l'API de géocodage au-delà de la limite de 50 requêtes par seconde et que le délai de 5 secondes qui s'en suit n'est pas écoulé.
Translation: 
>If the script calls the geocoding API without any particular precautions, with a frequency that exceeds the usage limit of 50 requests per second per IP, then:
>
>The first 50 calls are processed normally; The 51st call and subsequent calls are blocked as long as the script continues to …
=> Update doc : add quota for Base Adresse Nationale FR (`:ban_data_gouv_fr`)
