alexreisner/geocoder

lib/geocoder/results/nominatim.rb
While reverse geocoding some places with Nominatim, I figured out some more keywords that can might be useful for POI detection.
There's a lot more, but I these are quite frequent on returned results.
=> Added some more POI type options for nominatim's results

lib/geocoder/results/yandex.rb
I had a problem when a result kind was ```country``` and I tried to get the city name:
```undefined method `has_key?' for nil:NilClass```
Checking if ```address_details``` exist before asking if ```address_details``` has some key would prevent that problem.
=> Fix bug in yandex results

lib/geocoder.rb, lib/geocoder/configuration.rb, lib/geocoder/logger.rb, lib/geocoder/lookups/baidu.rb, lib/geocoder/lookups/baidu_ip.rb, lib/geocoder/lookups/base.rb, lib/geocoder/lookups/bing.rb, lib/geocoder/lookups/geocoder_ca.rb, lib/geocoder/lookups/geocodio.rb, lib/geocoder/lookups/google.rb, lib/geocoder/lookups/google_places_details.rb, lib/geocoder/lookups/mapquest.rb, lib/geocoder/lookups/maxmind.rb, lib/geocoder/lookups/maxmind_geoip2.rb, lib/geocoder/lookups/nominatim.rb, lib/geocoder/lookups/opencagedata.rb, lib/geocoder/lookups/pointpin.rb, lib/geocoder/lookups/postcode_anywhere_uk.rb, lib/geocoder/lookups/yahoo.rb, lib/geocoder/lookups/yandex.rb, test/unit/logger_test.rb
In response to #727 
I have followed the specifications from http://www.ruby-doc.org/stdlib-2.1.0/libdoc/logger/rdoc/Logger.html for the case when the user passes in a Logger to config
=> Adding Geocoder.log() 

lib/geocoder/results/geoip2.rb
=> Support maxminddb gem v0.1.7

test/unit/logger_test.rb, test/unit/lookup_test.rb, test/unit/lookups/google_places_details_test.rb, test/unit/lookups/pointpin_test.rb
=> Silence warnings using silence_warnings blocks

lib/geocoder/lookups/bing.rb, test/unit/cache_test.rb
=> Treat Bing overload responses as invalid

README.md
Bing stats are outdated. They changed the offering sadly.
=> Updated Bing offering

lib/geocoder/logger.rb
The type checking seems redundant.
=> logger configuration is incompatible with Rails.logger (not really)

README.md
Updated description with additional details
=> Updated geocodio description

README.md
:scissors: "reverse" as the paragraph is only about simple geocoding. The next one is about reverse geocoding.
=> Minor typo fix in the README

lib/geocoder/lookups/base.rb, lib/geocoder/results/pointpin.rb
=> Ruby warnings

README.md
See [this post](http://clubs.ya.ru/mapsapi/replies.xml?item_no=58741)
and also [documentation](https://tech.yandex.ru/maps/doc/geocoder/desc/concepts/input_params-docpage/) for the details
Sorry for unable to provide link to the english version.
Seems that changes are not reflected in the [english documentation](https://tech.yandex.com/maps/doc/geocoder/desc/concepts/input_params-docpage/) yet
=> Add changes in conditions of use yandex geocoding API to the README

lib/geocoder/calculations.rb
Very small addition to allow random_point_near to accept a `:seed` option
=> added random seed option to Geocoder::Calculations.random_point_near

README.md, lib/geocoder/lookup.rb, lib/geocoder/lookups/mapbox.rb, lib/geocoder/results/mapbox.rb, test/fixtures/mapbox_invalid_api_key, test/fixtures/mapbox_madison_square_garden, test/fixtures/mapbox_no_results, test/unit/lookup_test.rb, test/unit/lookups/mapbox_test.rb
Adds lookup using [mapbox](https://www.mapbox.com/developers/api/geocoding/)
=> Add Mapbox lookup service

lib/geocoder/results/mapbox.rb, test/unit/lookups/mapbox_test.rb
Refactor mapbox result and expland test coverage
=> Refactor Mapbox result & expand test coverage

Gemfile, gemfiles/Gemfile.rails3.2, gemfiles/Gemfile.rails4.1, gemfiles/Gemfile.ruby1.9.3
You can check my travis build results here: https://travis-ci.org/TrangPham/geocoder
Links to #937
=> Fix the mysql tests on travis.

lib/geocoder/configuration.rb, lib/geocoder/results/geoip2.rb, test/test_helper.rb, test/unit/lookups/geoip2_test.rb
=> Add locale support to GeoIP2 result display class

lib/geocoder/lookups/geoip2.rb
Also reduce object allocation :blush:
=> Refactor geoip2 lookup class file

lib/geocoder/results/esri.rb, test/unit/lookups/esri_test.rb
Added these attributes to esri result. They're nice to have. I also renamed some ambiguously-named variables.
=> Add place_name and place_type to esri result

README.md, lib/geocoder/lookup.rb, lib/geocoder/lookups/geoportail_lu.rb, lib/geocoder/results/geoportail_lu.rb, test/fixtures/geoportail_lu_boulevard_royal, test/fixtures/geoportail_lu_no_results, test/fixtures/geoportail_lu_reverse, test/test_helper.rb, test/unit/lookups/geoportail_lu_test.rb, test/unit/result_test.rb
As i met some problems with a rebase, i have created this new PR
This is the correction of PR https://github.com/alexreisner/geocoder/pull/963
All modifications are now  group into one commit :-)
Thank you
=> Add adapter for geoportail.lu (Luxembourg)

lib/geocoder/lookups/telize.rb
Telize offers an opensource version that can be run from a custom host. This should add support for it.
=> Support for custom telize endpoint

lib/geocoder/request.rb
see https://github.com/alexreisner/geocoder/issues/966#issuecomment-176004476
=> Include in ActionDispatch::Request instead of Rack:Request, closes #966

lib/geocoder/lookups/pelias.rb, test/unit/lookups/pelias_test.rb
I  implemented Mapzen reverse geocoding.
To resolve #1039 Mapzen reverse geocoding param error.
Thanks.
=> Add Mapzen reverse geocoding

lib/geocoder/request.rb
Can we test correct module inclusion in some way?
=> try Rack::Request if ActionDispatch::Request is not defined, fixes #1060

lib/geocoder/exceptions.rb, lib/geocoder/lookups/base.rb, test/test_helper.rb, test/unit/error_handling_test.rb
=> handles unreachable network exception

.travis.yml, Gemfile, gemfiles/Gemfile.rails3.2, gemfiles/Gemfile.rails4.1, gemfiles/Gemfile.ruby1.9.3, lib/geocoder/stores/active_record.rb, test/test_helper.rb, test/unit/near_test.rb
I think this is basically ready to incorporate, but…
* Is the travis setup right?
* Are the Gemfile changes right?
Maybe the CI run for this PR will tell us those things.
=> Use sqlite ruby math extensions if present

lib/geocoder/stores/base.rb, test/unit/mongoid_test.rb
=> Make geocoded? return false with single coordinate

lib/geocoder/lookups/opencagedata.rb, test/unit/lookups/opencagedata_test.rb
I added support for a bunch of optional opencage query parameters. Thought this could be interesting for other users as well. Feedback or suggestions are very welcome.
=> support for opencagedata optional parameters

README.md
Small change in wording in the readme.md
=> Spelling fix in the readme

lib/geocoder/results/yandex.rb, test/fixtures/yandex_black_sea, test/unit/lookups/yandex_test.rb
In the sea for example
[Fix #1131]
=> Now result.country doesn't fail f result is not in a country

test/unit/lookups/yandex_test.rb
=> Rename test case when there is no country in the yandex results

lib/geocoder/results/nominatim.rb
Here's an example:
```
http://nominatim.openstreetmap.org/details.php?place_id=118227317
```
The type is restaurant which is missing in the current list but we can get it from `@data['type']`
=> Place of interest can be referred from `place_type` for Nominatim result

lib/geocoder/results/yandex.rb
Add street and street_number methods to Yandex lookup
=> Add street and street_number methods to Yandex lookup

lib/generators/geocoder/config/templates/initializer.rb
cache must respond to `#del`, not `#keys`
=> fix comment describing the required cache interface

README.md, gemfiles/Gemfile.ruby1.9.3, lib/geocoder/lookup.rb, lib/geocoder/lookups/amap.rb, lib/geocoder/results/amap.rb, test/fixtures/amap_invalid_key, test/fixtures/amap_no_results, test/fixtures/amap_reverse, test/fixtures/amap_shanghai_pearl_tower, test/test_helper.rb, test/unit/lookup_test.rb
Added AMap (AutoNavi from Alibaba，高德地图) integration, lots of usage in China.
=> Added Amap(AutoNavi) integration: http://lbs.amap.com

lib/geocoder/results/here.rb
Here Map returns street and street number in result. I added two methods (like a google lookup result) `route` and `street_number`.
=> Add street and street number to Here's result 

README.md
For https://github.com/alexreisner/geocoder/issues/1038
v1.3.5 has host based on changelog
I thought this would be picked up by someone but since it took a while I might as well
=> Adding documentation for host option on telize

lib/geocoder/models/active_record.rb, lib/geocoder/stores/base.rb, test/unit/model_test.rb
For #1118 
Wondering if there's a better way to test this
Considering using `Mocha` gem to be able to check if method was called with certain values.
=> Adding params for geocoded_by and reverse_geocoded_by

lib/geocoder/lookups/opencagedata.rb
OpenCage recently added a new optional parameter "abbrv".
Some details: http://blog.opencagedata.com/post/160294347883/shrtr-pls
=> add support for abbrv param

README.md, lib/geocoder/lookups/google.rb
Enable you to get a result via a specific place ID
=> Support for Google's 'place_id' param

lib/generators/geocoder/maxmind/geolite_city_generator.rb, lib/generators/geocoder/maxmind/geolite_country_generator.rb, lib/generators/geocoder/maxmind/templates/migration/geolite_city.rb, lib/generators/geocoder/maxmind/templates/migration/geolite_country.rb, lib/generators/geocoder/migration_version.rb, test/db/migrate/001_create_test_schema.rb
In reference to issue https://github.com/alexreisner/geocoder/issues/1208
=> specify rails version for migrations

README.md
Add missing commas to hashes in test stubs.
=> Add missing commas in hashes

README.md, lib/geocoder/lookups/location_iq.rb, test/fixtures/location_iq_invalid_request, test/fixtures/location_iq_over_limit, test/fixtures/location_iq_request_denied, test/unit/lookups/location_iq_test.rb
Disclosure: I work at LocationIQ (Unwired Labs). This PR is sponsored by Unwired Labs.
=> Update LocationIQ geocoding provider with limits and handle errors

README.md, lib/geocoder/lookup.rb, lib/geocoder/lookups/db_ip_com.rb, lib/geocoder/results/db_ip_com.rb, test/fixtures/db_ip_com_23_255_240_0, test/fixtures/db_ip_com_invalid_key, test/test_helper.rb, test/unit/lookup_test.rb, test/unit/lookups/db_ip_com_test.rb
This PR is a continuation of https://github.com/alexreisner/geocoder/pull/1063, which seems to have been abandoned in 2016, and I'd like to help see it through to a release.
=> Add support for DB-IP.com geocoding service, take 2

.travis.yml
Reverts alexreisner/geocoder#1225
=> Revert "Removing ruby versions that are not supported anymore from our travis…"

test/mongoid_test_helper.rb, test/unit/mongoid_test.rb
=> Adding more mongoid model tests

lib/geocoder/request.rb, test/unit/request_test.rb
=> Handle IPv6 addresses when removing port numbers in request.location. Closes #1210

lib/geocoder/lookups/geocodio.rb
See https://geocod.io/docs/#changelog
=> Update geocod.io to use most recent API version

.travis.yml, test/unit/lookups/yandex_test.rb
This adds the latest ruby major versions to the travis config
=> add ruby 2.4 and 2.5 to travis

lib/geocoder/railtie.rb
Related GitHub issue: https://github.com/alexreisner/geocoder/issues/1318
=> Update Railtie initializer to run before config intializers

lib/geocoder/calculations.rb
341-348 degrees missing N value in 16-wind compass rose
Fixes  #1371
=> Fix: compass_point

lib/geocoder/lookups/base.rb
Closes https://github.com/alexreisner/geocoder/issues/1378
=> Rescue the Geocoder::NetworkError to stay consistent with the README.md

README_API_GUIDE.md, lib/geocoder/lookup.rb, lib/geocoder/lookups/ipregistry.rb, lib/geocoder/results/ipregistry.rb, test/fixtures/ipregistry_8_8_8_8, test/test_helper.rb, test/unit/lookup_test.rb, test/unit/lookups/ipregistry_test.rb
We have users who would like to use your great Ruby library with [Ipregistry](https://ipregistry.co). This PR adds support for this new service that is reliable and returns responses with very low latency worldwide.
=> Add support for Ipregistry

lib/maxmind_database.rb
resolves #1407 
I've updated Maxmind GeoLite URLs with new specified on the [GeoLite2 download page](https://dev.maxmind.com/geoip/geoip2/geolite2/)
=> Update Maxmind Geolite URLs

README_API_GUIDE.md
Source:
https://ipinfo.io/missingauth
I've got confused having a rate limit of 1k/day, so maybe this will be clearer having it mentioned here.
=> Update IPinfo quota information

lib/geocoder/lookups/tencent.rb
=> update Tencent status codes

lib/geocoder/lookups/esri.rb, test/unit/lookups/esri_test.rb
See https://developers.arcgis.com/rest/geocode/api-reference/geocoding-find-address-candidates.htm for more information
=> Added preferredLabelValues param for ESRI

README_API_GUIDE.md
It's much practical (and a bit ethical) to have the list alphabetically ordered.
Thanks
=> Sort API list in alphabetical order

README_API_GUIDE.md
- Updates broken links
- Add new optional params to the Google Places Search Service
=> Update Docs for Google Places API services

README_API_GUIDE.md, lib/geocoder/lookup.rb, lib/geocoder/lookups/geoapify.rb, lib/geocoder/results/geoapify.rb, test/fixtures/geoapify_invalid_key, test/fixtures/geoapify_invalid_request, test/fixtures/geoapify_madison_square_garden, test/fixtures/geoapify_no_results, test/fixtures/geoapify_reverse, test/test_helper.rb, test/unit/lookups/geoapify_test.rb
This adds support for [Geoapify](https://www.geoapify.com) Geocoding API.
=> Add support for Geoapify

README_API_GUIDE.md, lib/geocoder/lookup.rb, lib/geocoder/lookups/photon.rb, lib/geocoder/results/photon.rb, test/fixtures/photon_invalid_request, test/fixtures/photon_madison_square_garden, test/fixtures/photon_no_results, test/fixtures/photon_reverse, test/test_helper.rb, test/unit/lookups/photon_test.rb
This adds support for [Photon](http://photon.komoot.de/) Geocoding API.
=> Add support for Photon

lib/geocoder/cache_stores/generic.rb, lib/geocoder/cache_stores/redis.rb
=> Fix: uninitialized constant Geocoder::CacheStore::Base.

.github/workflows/default.yml, test/unit/lookups/here_test.rb
Hey @alexreisner here's my attempt at getting this project back to running on CI! I'm using GitHub Actions here per your comment on that other PR but I'm less familiar with it than say CircleCI so if there's any feedback I'm totally open to changes!
You'll also notice that I had to mark a test as pending because I couldn't figure out why it was failing. You can see that failure here:
https://github.com/jonallured/geocoder/runs/6627303485?check_suite_focus=true
Seems bad to pend but worse to not have CI running at all so I took the tradeoff. What do you think? I also couldn't get other Ruby versions to run but we can iterate from here!
=> Add github action for running tests

README.md
=> Remove mention of auto expiry cache in the README

README_API_GUIDE.md
Added the region key which is required for authentication using `aws-sdk-locationservice` gem.
=> Update Amazon Location Services instructions in README_API_GUIDE.md

lib/maxmind_database.rb
This is intended to fix #1651.
=> Make `Geocoder::MaxmindDatabase.archive_edition` Method Public
